name: Golang CI
run-name: Golang CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directories: [ ./resttail-generate, . ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.4

      - name: Setup Go Environment
        uses: actions/setup-go@v5.0.0
        with:
          go-version: '>=1.22.2'
          cache: false

      - name: Run golangCI-lint
        uses: golangci/golangci-lint-action@v5.0.0
        with:
          version: latest
          args: --config ./.golangci.yaml . ./resttail-generate
          working-directory: ${{ matrix.directories }}